server:
  port: 8104

spring:
  application:
    name: ywy-study
  config:
    import: optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:yanyan}
        ip: ${NACOS_IP:127.0.0.1}
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:yanyan}
        file-extension: yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDR:127.0.0.1:3306}/ywy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_ADDR:127.0.0.1}
      port: ${REDIS_PORT:16379}
      database: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

ywy:
  study:
    anki-prefix: "anki:due:"
    checkin-prefix: "checkin:"

management:
  endpoints:
    web:
      exposure:
        include: health,info